// src/components/contact.tsx
import { social } from "@/lib/portfolio-data";

export function ContactSection() {
  return (
    <section id="contact" className="mx-auto mb-25 max-w-150 text-center">
      <h2 className="relative my-2.5 mb-5 w-full whitespace-nowrap font-mono text-[1.6rem] font-normal text-[#64ffda] before:relative before:mr-2.5 before:font-normal before:content-['0'_counter(section)_'.']">What is Next?</h2>
      <h2 className="text-[clamp(40px,5vw,60px)]">Get In Touch</h2>
      <p>
        Although I am not currently looking for any new opportunities, my inbox is always open. Whether you have a question or just
        want to say hi, I will try my best to get back to you!
      </p>
      <a
        className="mt-12.5 rounded-[0.4rem] border border-[#64ffda] bg-transparent px-7 py-5 font-mono text-[1.4rem] leading-none text-[#64ffda] transition-all hover:-translate-x-1.25 hover:-translate-y-1.25 hover:shadow-[4px_4px_0_0_#64ffda]"
        href={`mailto:${social.mail}`}
        rel="noopener noreferrer"
        target="_blank"
      >
        Say Hello
      </a>
    </section>
  );
}

// src/app/components/widgets/contact/contact.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'wgt-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.scss']
})
export class ContactComponent {

}

<section
  id="contact"
  class="contact__StyledContact fMdyDu"
  data-sr-id="15"
  style="
    visibility: visible;
    opacity: 1;
    transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);
    transition: opacity 0.5s cubic-bezier(0.645, 0.045, 0.355, 1) 0.2s,
      transform 0.5s cubic-bezier(0.645, 0.045, 0.355, 1) 0.2s;
  "
>
  <h2 class="contact__StyledContact-numbered-heading contact__StyledContact-overline">What’s Next?</h2>
  <h2 class="contact__StyledContact-title">Get In Touch</h2>
  <p>
    Although I’m not currently looking for any new opportunities, my inbox is
    always open. Whether you have a question or just want to say hi, I’ll try my
    best to get back to you!
  </p>
  <a
    class="contact__StyledContact-email-link"
    href="mailto:vinitsharma9876@gmail.com"
    rel="noopener noreferrer"
    target="_blank"
    >Say Hello</a
  >
</section>
