// src/app/components/widgets/about/about.component.ts
import { Component } from '@angular/core';
import { About } from 'src/app/models/about-model';
import { AppConfigService } from 'src/app/services/app-config.service';

@Component({
  selector: 'wgt-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.scss']
})
export class AboutComponent {
  public readonly aboutStaticData: About = this.appConfig.about;

  constructor (private appConfig: AppConfigService) {};
}

<section
  id="about"
  class="about__wrapper"
  data-sr-id="0"
  style="
    visibility: visible;
    opacity: 1;
    transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);
    transition: opacity 0.5s cubic-bezier(0.645, 0.045, 0.355, 1) 0.2s,
      transform 0.5s cubic-bezier(0.645, 0.045, 0.355, 1) 0.2s;
  "
>
  <h2 class="numbered-heading">About Me</h2>
  <div class="inner">
    <div>
      <div>
        <p>
          Hello! My name is {{ aboutStaticData.name }} and {{ aboutStaticData.description }}
        </p>
        <p>
          <span *ngIf="aboutStaticData.notableExperiences.length"> Fast-forward to today, and I’ve had the privilege of working at </span>
          <a *ngFor="let notable_experience of aboutStaticData.notableExperiences; let i=index"
          class="a__highlighted_underlined"
            [href]= "notable_experience.href"
            rel="noopener noreferrer"
            target="_blank">
            {{ notable_experience.display_text }}{{i === aboutStaticData.notableExperiences.length - 1 ? "." : ","}}
          </a>
          My main focus these days is building accessible, inclusive products
          and digital experiences at
          <a
            class="a__highlighted_underlined"
            [href]="aboutStaticData.currentExperience.href"
            rel="noopener noreferrer"
            target="_blank"
            >{{aboutStaticData.currentExperience.name}}</a
          >
          for a variety of clients.
        </p>
        <!-- <p>
          I also recently
          <a
            class="a__highlighted_underlined"
            href=""
            rel="noopener noreferrer"
            target="_blank"
            >launched a course</a
          >
          that covers everything ...
        </p> -->
        <p>Here are a few technologies I’ve been working with recently:</p>
      </div>
      <ul class="about__skills-list">
        <li class="about__skills-list-li" *ngFor="let skill of aboutStaticData.skills">{{ skill }}</li>
      </ul>
    </div>
    <div class="about__styledPic positioner">
      <div class="about__styledPic-wrapper">
        <div class="about__image-wrapper">
          <div style="max-width: 500px; display: block">
            <img
              alt=""
              role="presentation"
              aria-hidden="true"
              src="data:image/svg+xml;charset=utf-8,%3Csvg height='500' width='500' xmlns='http://www.w3.org/2000/svg' version='1.1'%3E%3C/svg%3E"
              style="max-width: 100%; display: block; position: static"
            />
          </div>
          <div
            aria-hidden="true"
            data-placeholder-image=""
            style="
              opacity: 0;
              transition: opacity 500ms linear 0s;
              background-color: rgb(232, 232, 232);
              position: absolute;
              inset: 0px;
              object-fit: cover;
            "
          ></div>
          <!-- <img src="/src/assets/images/pic.jpg"/> -->
          <picture>
            <!-- <source
              type="image/avif"
              srcset="
                /static/30a645f7db6038f83287d0c6042d3b2b/aebc8/me.avif 125w,
                /static/30a645f7db6038f83287d0c6042d3b2b/6b255/me.avif 250w,
                /static/30a645f7db6038f83287d0c6042d3b2b/f9526/me.avif 500w
              "
              sizes="(min-width: 500px) 500px, 100vw" />
            <source
              type="image/webp"
              srcset="
                /static/30a645f7db6038f83287d0c6042d3b2b/4155f/me.webp 125w,
                /static/30a645f7db6038f83287d0c6042d3b2b/02deb/me.webp 250w,
                /static/30a645f7db6038f83287d0c6042d3b2b/1ee78/me.webp 500w
              "
              sizes="(min-width: 500px) 500px, 100vw" />
            <img
              width="500"
              height="500"
              data-main-image=""
              sizes="(min-width: 500px) 500px, 100vw"
              decoding="async"
              src="/static/30a645f7db6038f83287d0c6042d3b2b/25f3c/me.jpg"
              srcset="
                /static/30a645f7db6038f83287d0c6042d3b2b/2dd75/me.jpg 125w,
                /static/30a645f7db6038f83287d0c6042d3b2b/754ad/me.jpg 250w,
                /static/30a645f7db6038f83287d0c6042d3b2b/25f3c/me.jpg 500w
              "
              alt="Headshot"
              style="object-fit: cover; opacity: 1" /> -->
          <img src="../../../../assets/images/pic.jpg" width="500"
          height="500" alt="Headshot" style="object-fit: cover; opacity: 1"/>
              </picture>
          <!-- <noscript></noscript> -->
        </div>
      </div>
    </div>
  </div>
</section>

// src/components/about.tsx
import { about } from "@/lib/portfolio-data";

export function AboutSection() {
  return (
    <section id="about" className="max-w-225">
      <h2 className="numbered-heading">About Me</h2>
      <div className="inner">
        <div>
          <div>
            <p>
              Hello! My name is {about.name} and {about.description}
            </p>
            <p>
              {about.notableExperiences.length > 0 ? "Fast-forward to today, and I have had the privilege of working at " : ""}
              {about.notableExperiences.map((experience, index) => (
                <a key={experience.name} className="a-highlighted-underlined" href={experience.href} rel="noopener noreferrer" target="_blank">
                  {experience.displayText}
                  {index === about.notableExperiences.length - 1 ? "." : ","}
                </a>
              ))}
              My main focus these days is building accessible, inclusive products and digital experiences at{" "}
              <a className="a-highlighted-underlined" href={about.currentExperience.href} rel="noopener noreferrer" target="_blank">
                {about.currentExperience.name}
              </a>{" "}
              for a variety of clients.
            </p>
            <p>Here are a few technologies I have been working with recently:</p>
          </div>
          <ul className="mt-5 grid list-none grid-cols-[repeat(2,minmax(140px,200px))] gap-x-2.5 gap-y-0 overflow-hidden p-0">
            {about.skills.map((skill) => (
              <li key={skill} className="relative mb-2.5 pl-5 font-mono text-[1.3rem] before:absolute before:left-0 before:text-[1.4rem] before:text-[#64ffda] before:content-['▹']">
                {skill}
              </li>
            ))}
          </ul>
        </div>
        <div className="relative max-w-75">
          <div className="group relative block w-full rounded-[0.4rem] bg-[#64ffda] shadow-[0_10px_30px_-15px_rgba(2,12,27,0.7)] transition-all hover:-translate-x-1 hover:-translate-y-1 hover:shadow-[0_20px_30px_-15px_rgba(2,12,27,0.7)] before:absolute before:left-0 before:top-0 before:block before:h-full before:w-full before:rounded-[0.4rem] before:bg-[#0a192f] before:mix-blend-screen before:content-[''] after:absolute after:left-5 after:top-5 after:-z-10 after:block after:h-full after:w-full after:rounded-[0.4rem] after:border-2 after:border-[#64ffda] after:content-[''] hover:after:left-3.75 hover:after:top-3.75 hover:after:translate-x-3 hover:after:translate-y-3">
            <div className="relative inline-block w-full max-w-full overflow-hidden rounded-[0.4rem] align-middle filter-[grayscale(100%)_contrast(1)] mix-blend-multiply transition-all group-hover:filter-none group-hover:mix-blend-normal">
              <img src="/images/pic.jpg" width={500} height={500} alt="Headshot" style={{ objectFit: "cover", opacity: 1 }} />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
